version: '3'
services:
  php:
    image: php:7.3-apache
    volumes:
        - ./www:/ver/www/html
    ports:
        - 8000:80
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASS: db_test